### ISSUE TITLE
Conflict with questing addons

### ISSUE THREAD

**Issue by MubarakHAlketbi** [stpain/Guildbook_ClassicEra#2] opened 2023-12-12 15:43 UTC
currently Guildbook Era addon causes conflict with quest addons such as restedXP guides and Questie 

it prevents them from updating progress.

i will do further diagnosing

**Comment by stpain** [comment] 2023-12-12 15:49
I would be very interested in how Guildbook is doing is. Here is a comment from another addon dev regarding quests.

_I have no idea
Forgot to check Journalator for the quest to see if it logged it sooner/later than Questie
It is logged now when I checked
Checked the Questie logs, Journalator and Questie noticed the quest completion at the same time (08:05, UK time)
So I'd say this is a Blizzard bug delaying quests reported as completed_

Of course should you find an issue it will be fixed as soon as possible

**Comment by MyTechnoHunter** [comment] 2023-12-12 18:00
> currently Guildbook Era addon causes conflict with quest addons such as restedXP guides and Questie
> 
> it prevents them from updating progress.
> 
> i will do further diagnosing

Hi, TechnoHunter from Questie here, any details as to what you mean by preventing updating progress? 
Screenshots are helpful!

**Comment by MubarakHAlketbi** [comment] 2023-12-12 18:35
> > currently Guildbook Era addon causes conflict with quest addons such as restedXP guides and Questie
> > it prevents them from updating progress.
> > i will do further diagnosing
> 
> Hi, TechnoHunter from Questie here, any details as to what you mean by preventing updating progress? Screenshots are helpful!

say for example i would loot "Liuetenant's Insignia" for the quest "Hidden Enemies", after looting it, in questie it will still show 0/1

i will turn guildbook again and try to get a screenshot.

Edit: although it could be something that has been fixed with the latest updates.

the uploaded picture is for RestedXP

![WowClassic_QTqZUMktsw](https://github.com/stpain/Guildbook_ClassicEra/assets/2147851/ad1ea84a-733a-45a3-83ea-31bf1e28110d)

**Comment by stpain** [comment] 2023-12-12 19:30
What was updated. I find it hard to agree that this is related to Guildbook specifically. The addons don't really share much in common or do similar things. Guildbook does scan bag items but then so does a hundred other addons, it also scans the quest log but does little more than look.

Of course if there is something causing a conflict that can be found I will attempt to fix it.

**Comment by MubarakHAlketbi** [comment] 2023-12-12 20:05
> What was updated. I find it hard to agree that this is related to Guildbook specifically. The addons don't really share much in common or do similar things. Guildbook does scan bag items but then so does a hundred other addons, it also scans the quest log but does little more than look.
> 
> Of course if there is something causing a conflict that can be found I will attempt to fix it.

it is the only addon that when i toggle on will result in this issue.

**Comment by MyTechnoHunter** [comment] 2023-12-12 23:51
> > Hi, TechnoHunter from Questie here, any details as to what you mean by preventing updating progress? Screenshots are helpful!
> 
> say for example i would loot "Liuetenant's Insignia" for the quest "Hidden Enemies", after looting it, in questie it will still show 0/1
> 
> i will turn guildbook again and try to get a screenshot.
> 
> Edit: although it could be something that has been fixed with the latest updates.
> 
> the uploaded picture is for RestedXP
> 
> ![WowClassic_QTqZUMktsw](https://private-user-images.githubusercontent.com/2147851/289969878-ad1ea84a-733a-45a3-83ea-31bf1e28110d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MjUxMjEsIm5iZiI6MTcwMjQyNDgyMSwicGF0aCI6Ii8yMTQ3ODUxLzI4OTk2OTg3OC1hZDFlYTg0YS03MzNhLTQ1YTMtODNlYS0zMWJmMWUyODExMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMjM0NzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzYwOWE5YzNiMTVjZTk3Nzg5ZDFjNTI5MDA3MjRlYjY2YjM4MGEyNTY4MjAzNDhkMmZjYTk3ZWY4NTRhYmQ3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8BlK_XDsO59r8Z2DUzlmy77HuLEb1u6U5DF1AVvNU3o)

Any pics with Questie would be helpful 
I use Questie and Guildbook and haven't noticed the behavior mentioned

**Comment by stpain** [comment] 2023-12-13 14:41
Any further issues with this?

**Comment by Mishura4** [comment] 2023-12-13 17:22
I believe this may be related, but I find that with Guildbook era on, the quest log keeps collapsing by itself, as if I had clicked on this buttton:
![image](https://github.com/stpain/Guildbook_ClassicEra/assets/809711/e401886d-9d81-4f5d-b740-12a4de142263)

This does happen with Guildbook era as the *only enabled addon*.

Steps to reproduce (on [latest version](https://www.curseforge.com/wow/addons/guildbook_classicera/files/4946813)):
- Disable all addons except Guildbook era
- Log in or /reload
- Open quest log, see how it's collapsed
- Click the button to expand all categories as in the image above
- /reload
- Open quest log, see how it's collapsed

This seems to happen periodically on its own as well, ~~perhaps on changing zones~~?

Now disable Guildbook, repeat the steps and see how the quest log does not automatically collapse as per Vanilla behavior.

Culprit seems to be this
https://github.com/stpain/Guildbook_ClassicEra/blob/7ed6d0cd8908711ba34cd64bd25a55dccfc7a447/Views/Dailies/Dailies.lua#L129

**Comment by MyTechnoHunter** [comment] 2023-12-13 18:26
oof.. interesting

**Comment by stpain** [comment] 2023-12-13 20:04
Yes that does collapse the log, i expand before scanning then collapse after. I need to see if there is an api to check if its open/closed first then set it back to that after

**Comment by stpain** [comment] 2023-12-13 20:05
Would that cause an issue with quest tracking though? I'd assume other addons need to expand before scanning as well?

**Comment by Mishura4** [comment] 2023-12-14 21:46
Yes it appears removing that line fixes the issues with other addons.

**Comment by MyTechnoHunter** [comment] 2023-12-14 21:50
> Yes that does collapse the log, i expand before scanning then collapse after. I need to see if there is an api to check if its open/closed first then set it back to that after

There isn't, would need manual looping, object with state saved, so on..

**Comment by stpain** [comment] 2023-12-14 21:51
Or maybe just expand all and be done with it? If other addons require it to be open anyways?

**Comment by MyTechnoHunter** [comment] 2023-12-14 23:33
> Or maybe just expand all and be done with it? If other addons require it to be open anyways?

Might be simpler.. altoholic does the loop/save method for professions, if I recall

The methods above are expand collapse all, not per entry.. any clue if there is an API for singleton?

**Closed as completed** 2023-12-24 19:54 UTC
